name: Deploy lemniscata.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COMMANDCORE_HOST }}
          username: 'redstone'
          key: ${{ secrets.COMMANDCORE_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/lemniscata/core/
            git reset --hard
            git pull origin main
            cd /var/www/lemniscata/core/backend/
            pnpm install
            sudo systemctl restart webapi.lemniscata
            cd /var/www/lemniscata/core/cartago/
            pnpm install